<a href="https://colab.research.google.com/github/anurag-23werty/AGE_GNEDER-RECONGNISATION/blob/main/TNelections.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files

uploaded = files.upload()

Saving constituency_master.csv to constituency_master.csv
Saving tn_2021_results.csv to tn_2021_results.csv
Saving tn_2026_results.csv to tn_2026_results.csv

In [2]:
from google.colab import files

uploaded = files.upload()

Saving tn_2026_votes.csv to tn_2026_votes.csv

In [3]:
from google.colab import files

uploaded = files.upload()

Saving tn_2026_total_electors.csv to tn_2026_total_electors.csv

In [4]:
import pandas as pd

In [5]:
df21 = pd.read_csv("tn_2021_results.csv")
df26 = pd.read_csv("tn_2026_results.csv")
master = pd.read_csv("constituency_master.csv")

In [6]:
print(df21.shape)
print(df26.shape)
print(master.shape)

print(df21.columns)
print(df26.columns)
print(master.columns)

(4232, 8)
(4257, 8)
(234, 5)
Index(['constituency', 'ac_number', 'candidate', 'party', 'votes', 'turnout',
       'reserved', 'region'],
      dtype='object')
Index(['constituency', 'ac_number', 'candidate', 'party', 'votes', 'turnout',
       'reserved', 'region'],
      dtype='object')
Index(['ac_number', 'constituency', 'district', 'region', 'reserved'], dtype='object')

In [7]:
print(df21.isnull().sum())

print(df26.isnull().sum())

print(master.isnull().sum())

constituency    0
ac_number       0
candidate       0
party           0
votes           0
turnout         0
reserved        0
region          0
dtype: int64
constituency       0
ac_number          0
candidate          0
party              0
votes              0
turnout         4257
reserved           0
region             0
dtype: int64
ac_number       0
constituency    0
district        0
region          0
reserved        0
dtype: int64

In [8]:
df21.sample(10)

,constituency,ac_number,candidate,party,votes,turnout,reserved,region
331,Egmore,16,V.SEKAR,IND,28,61.13,SC,Chennai Metro
3400,Madurai East,189,PRABAHARAN M,Bahujan Dravida Party,112,71.34,GEN,South
2471,Karur,135,DHANALAKSHMI.M,Ganasangam Party of India,105,83.57,GEN,Kongu
3036,Thiruthuraipundi,166,PARAMASIVAM K,IND,476,76.74,SC,Delta
1437,Sankarapuram,79,UTHAYAKUMAR A,IND,166,79.58,GEN,Central
486,Virugampakkam,22,S.R.DINESH KUMAR,Anna MGR Dravida Makkal Kalgam,41,57.59,GEN,Chennai Metro
1662,Veerapandi,91,"CHINNANANN, M.",BSP,361,85.64,GEN,Central
2862,Neyveli,153,None Of The Above,NOTA,1171,74.25,GEN,Central
1386,Tirukkoyilur,76,RAJINI VR,Naadaalum Makkal Katchi,231,76.27,GEN,Central
3871,Vilathikulam,213,ARUMUGAPERUMAL K,IND,268,76.52,GEN,South

In [9]:
df26.sample(10)

,constituency,ac_number,candidate,party,votes,turnout,reserved,region
573,Mylapore,25,PARTHIPAN. G,IND,64,NaN,GEN,Chennai Metro
1828,Paramathi-Velur,95,MOORTHIY K S,DMK,61041,NaN,GEN,Central
2755,Thiruverumbur,142,CHARLES. S,IND,101,NaN,GEN,Delta
1361,Gingee,70,PERUMAL N,Aanaithinthiya Jananayaka Pathukappu Kazhagam,285,NaN,GEN,Central
1646,Edappadi,86,GOVINDARAJ.V,Tamizhaga Vaazhvurimai Katchi,1662,NaN,GEN,Central
2228,Coimbatore (North),118,R. SETHURAGUNATHAN,IND,60,NaN,GEN,Kongu
2563,Karur,135,MARIAMMAL. P.M,IND,16,NaN,GEN,Kongu
4181,Nagercoil,230,AUSTIN,DMK,69880,NaN,GEN,South
3627,Bodinayakanur,200,NARAYANASAMY V.T.,AIADMK,41286,NaN,GEN,South
3392,Karaikudi,184,PANDI. S,IND,361,NaN,GEN,South

In [10]:
master.sample(10)

     ac_number     constituency      district         region reserved
74          75       Vikravandi    Villupuram        Central      GEN
19          20  Thousand Lights       Chennai  Chennai Metro      GEN
81          82            Attur         Salem        Central       SC
99         100      Modakurichi         Erode          Kongu      GEN
193        194     Madurai West       Madurai          South      GEN
207        208        Tiruchuli  Virudhunagar          South      GEN
104        105         Anthiyur         Erode          Kongu      GEN
175        176     Pattukkottai     Thanjavur          Delta      GEN
75          76     Tirukkoyilur    Villupuram        Central      GEN
42          43          Vellore       Vellore          North      GEN

In [11]:
df21["constituency"].unique()

array(['Gummidipundi', 'Ponneri', 'Tiruttani', 'Thiruvallur',
       'Poonamallee', 'Avadi', 'Maduravoyal', 'Ambattur', 'Madavaram',
       'Thiruvottiyur', 'Dr. Radhakrishnan Nagar', 'Perambur', 'Kolathur',
       'Villivakkam', 'Thiru-Vi-Ka-Nagar', 'Egmore', 'Royapuram',
       'Harbour', 'Chepauk-Thiruvallikeni', 'Thousand Lights',
       'Anna Nagar', 'Virugampakkam', 'Saidapet', 'Theayagaraya Nagar',
       'Mylapore', 'Velachery', 'Shozhinganallur', 'Alandur',
       'Sriperumbudur', 'Pallavaram', 'Tambaram', 'Chengalpattu',
       'Thiruporur', 'Cheyyur', 'Maduranthakam', 'Uthiramerur',
       'Kancheepuram', 'Arakonam', 'Sholinghur', 'Katpadi', 'Ranipet',
       'Arcot', 'Vellore', 'Anaikattu', 'Kilvaithinankuppam',
       'Gudiyatham', 'Vaniayambadi', 'Ambur', 'Jolarpet', 'Tiruppattur',
       'Uthangarai', 'Bargur', 'Krishnagiri', 'Veppanahalli', 'Hosur',
       'Thalli', 'Palacode', 'Pennagaram', 'Dharmapuri',
       'Pappireddippatti', 'Harur', 'Chengam', 'Tiruvannamalai',
       'Kilpennathur', 'Kalasapakkam', 'Polur', 'Arani', 'Cheyyar',
       'Vandavasi', 'Gingee', 'Mailam', 'Tindivanam', 'Vanur',
       'Villupuram', 'Vikravandi', 'Tirukkoyilur', 'Ulundurpet',
       'Rishivandiam', 'Sankarapuram', 'Kallakurichi', 'Gangavalli',
       'Attur', 'Yercaud', 'Omalur', 'Mettur', 'Edapadi', 'Sankari',
       'Salem (West)', 'Salem (North)', 'Salem (South)', 'Veerapandi',
       'Rasipuram', 'Sendamangalam', 'Namakkal', 'Paramathi-Velur',
       'Tiruchengode', 'Kumarapalayam', 'Erode (East)', 'Erode (West)',
       'Modakurichi', 'Dharapuram', 'Kangayam', 'Perundurai', 'Bhavani',
       'Anthiyur', 'Gobichettipalayam', 'Bhavanisagar', 'Udhagamandalam',
       'Gudalur', 'Coonoor', 'Mettupalayam', 'Avanashi',
       'Tiruppur (North)', 'Tiruppur (South)', 'Palladam', 'Sulur',
       'Kavundampalayam', 'Coimbatore North', 'Thondamuthur',
       'Coimbatore South', 'Singanallur', 'Kinathukadavu', 'Pollachi',
       'Valparai', 'Udumalpet', 'Madathukulam', 'Palani', 'Oddanchatram',
       'Athoor', 'Nilakottai', 'Natham', 'Dindigul', 'Vedasandur',
       'Aravakurichi', 'Karur', 'Krishnarayapuram', 'Kulithalai',
       'Manapparai', 'Srirangam', 'Tiruchirapalli (West)',
       'Tiruchirapalli (East)', 'Thiruverambur', 'Lalgudi',
       'Manachanallur', 'Musiri', 'Thuraiyur', 'Perambalur', 'Kunnam',
       'Ariyalur', 'Jayankondam', 'Tittakudi', 'Vriddhachalam', 'Neyveli',
       'Panruti', 'Cuddalore', 'Kurinjipadi', 'Bhuvanagiri',
       'Chidambaram', 'Kattumannarkoil', 'Sirkali', 'Mayiladuthurai',
       'Poompuhar', 'Nagapattinam', 'Kilvelur', 'Vedaranyam',
       'Thiruthuraipundi', 'Mannargudi', 'Thiruvarur', 'Nannilam',
       'Thiruvidamarudur', 'Kumbakonam', 'Papanasam', 'Thiruvaiyaru',
       'Thanjavur', 'Orathanad', 'Pattukkottai', 'Peravurani',
       'Gandharvakottai', 'Viralimalai', 'Pudukkottai', 'Thirumayam',
       'Alangudi', 'Arantangi', 'Karaikudi', 'Sivaganga', 'Manamadurai',
       'Melur', 'Madurai East', 'Sholavandan', 'Madurai North',
       'Madurai South', 'Madurai Central', 'Madurai West',
       'Thiruparankundram', 'Thirumangalam', 'Usilampatti', 'Andipatti',
       'Periyakulam', 'Bodinayakanur', 'Cumbum', 'Rajapalayam',
       'Srivilliputhur', 'Sattur', 'Sivakasi', 'Virudhunagar',
       'Aruppukottai', 'Tiruchuli', 'Paramakudi', 'Tiruvadanai',
       'Ramanathapuram', 'Mudukulathur', 'Vilathikulam', 'Thoothukkudi',
       'Tiruchendur', 'Srivaikuntam', 'Ottapidaram', 'Kovilpatti',
       'Sankarankovil', 'Vasudevanallur', 'Kadayanallur', 'Tenkasi',
       'Alangulam', 'Tirunelveli', 'Ambasamudram', 'Palayamcottai',
       'Nanguneri', 'Radhapuram', 'Kanniyakumari', 'Nagercoil',
       'Colachel', 'Padmanabhapuram', 'Vilavancode', 'Killiyoor'],
      dtype=object)

In [12]:
for df in [df21, df26, master]:
    df["constituency"] = (
        df["constituency"]
        .str.strip()
    )
set_21 = set(df21["constituency"])
set_26 = set(df26["constituency"])
set_master = set(master["constituency"])

print("Present in 2021 but missing in 2026:")
print(set_21 - set_26)

print("\nPresent in 2026 but missing in 2021:")
print(set_26 - set_21)

print("\nPresent in results but missing in master:")
print((set_21 | set_26) - set_master)

Present in 2021 but missing in 2026:
{'Arantangi', 'Orathanad', 'Tiruchirapalli (West)', 'Arakonam', 'Thiruthuraipundi', 'Gudiyatham', 'Thiruverambur', 'Theayagaraya Nagar', 'Thiruvidamarudur', 'Tiruchirapalli (East)', 'Palayamcottai', 'Udumalpet', 'Maduranthakam', 'Rishivandiam', 'Palacode', 'Mettupalayam', 'Modakurichi', 'Edapadi', 'Villupuram', 'Coimbatore South', 'Ulundurpet', 'Nilakottai', 'Sirkali', 'Sendamangalam', 'Tiruchengode', 'Sholinghur', 'Aruppukottai', 'Mudukulathur', 'Pappireddippatti', 'Dr. Radhakrishnan Nagar', 'Gummidipundi', 'Colachel', 'Vaniayambadi', 'Coimbatore North'}

Present in 2026 but missing in 2021:
{'Dr.Radhakrishnan Nagar', 'Palayamkottai', 'Palacodu', 'Arakkonam', 'Tiruchengodu', 'Aranthangi', 'Aruppukkottai', 'Thiruverumbur', 'Edappadi', 'Modakkurichi', 'Madurantakam', 'Thiruthuraipoondi', 'Ulundurpettai', 'Thiyagarayanagar', 'Orathanadu', 'Tiruchirappalli (West)', 'Viluppuram', 'Coimbatore (South)', 'Gudiyattam', 'Mudhukulathur', 'Gummidipoondi', 'Colachal', 'Nilakkottai', 'Senthamangalam', 'Sholingur', 'Sirkazhi', 'Tiruchirappalli (East)', 'Thiruvidaimarudur', 'Pappireddipatti', 'Udumalaipettai', 'Rishivandiyam', 'Mettuppalayam', 'Coimbatore (North)', 'Vaniyambadi'}

Present in results but missing in master:
{'Dr.Radhakrishnan Nagar', 'Palayamkottai', 'Palacodu', 'Arakkonam', 'Tiruchengodu', 'Aranthangi', 'Aruppukkottai', 'Thiruverumbur', 'Edappadi', 'Modakkurichi', 'Madurantakam', 'Thiruthuraipoondi', 'Ulundurpettai', 'Thiyagarayanagar', 'Orathanadu', 'Tiruchirappalli (West)', 'Viluppuram', 'Coimbatore (South)', 'Gudiyattam', 'Mudhukulathur', 'Gummidipoondi', 'Colachal', 'Nilakkottai', 'Sholingur', 'Sirkazhi', 'Senthamangalam', 'Tiruchirappalli (East)', 'Thiruvidaimarudur', 'Pappireddipatti', 'Udumalaipettai', 'Rishivandiyam', 'Mettuppalayam', 'Coimbatore (North)', 'Vaniyambadi'}

In [13]:
for df in [df21, df26, master]:
    df["constituency"] = (
        df["constituency"]
        .str.strip()
    )

In [14]:
constituency_map = {

'Gummidipoondi':'Gummidipundi',
'Palayamkottai':'Palayamcottai',
'Arakkonam':'Arakonam',
'Sholingur':'Sholinghur',
'Viluppuram':'Villupuram',
'Thiyagarayanagar':'Theayagaraya Nagar',
'Dr.Radhakrishnan Nagar':'Dr. Radhakrishnan Nagar',
'Coimbatore (North)':'Coimbatore North',
'Coimbatore (South)':'Coimbatore South',
'Tiruchirappalli (West)':'Tiruchirapalli (West)',
'Tiruchirappalli (East)':'Tiruchirapalli (East)',
'Senthamangalam':'Sendamangalam',
'Madurantakam':'Maduranthakam',
'Tiruchengodu':'Tiruchengode',
'Rishivandiyam':'Rishivandiam',
'Vaniyambadi':'Vaniayambadi',
'Palacodu':'Palacode',
'Aruppukkottai':'Aruppukottai',
'Edappadi':'Edapadi',
'Ulundurpettai':'Ulundurpet',
'Nilakkottai':'Nilakottai',
'Sirkazhi':'Sirkali',
'Pappireddipatti':'Pappireddippatti',
'Colachal':'Colachel',
'Gudiyattam':'Gudiyatham',
'Mettuppalayam':'Mettupalayam',
'Modakkurichi':'Modakurichi',
'Thiruverumbur':'Thiruverambur',
'Thiruvidaimarudur':'Thiruvidamarudur',
'Mudhukulathur':'Mudukulathur',
'Udumalaipettai':'Udumalpet',
'Aranthangi':'Arantangi',
'Orathanadu':'Orathanad',
'Thiruthuraipoondi':'Thiruthuraipundi'
}

In [15]:
for df in [df21, df26, master]:

    df['constituency'] = (
        df['constituency']
        .replace(constituency_map)
        .str.strip()
    )

In [16]:
set_21 = set(df21["constituency"])
set_26 = set(df26["constituency"])
set_master = set(master["constituency"])

print(set_21-set_26)
print(set_26-set_21)
print((set_21|set_26)-set_master)

set()
set()
set()

In [17]:
dftn = pd.read_csv("tn_2026_votes.csv")

In [18]:
dftn.sample(10)

,constituency_no,constituency_name,evm_votes,postal_votes,total_votes_polled,status,last_updated,source_url,error
212,213,VILATHIKULAM,172556.0,2258.0,174814.0,Status of EVM Round: 20 /20,Last Updated at 04:18 PM On 05/05/2026,https://results.eci.gov.in/ResultAcGenMay2026/...,NaN
11,12,PERAMBUR,203072.0,1312.0,204384.0,Status of EVM Round: 23 /23,Last Updated at 04:18 PM On 05/05/2026,https://results.eci.gov.in/ResultAcGenMay2026/...,NaN
33,34,CHEYYUR,185623.0,1961.0,187584.0,Status of EVM Round: 22 /22,Last Updated at 04:18 PM On 05/05/2026,https://results.eci.gov.in/ResultAcGenMay2026/...,NaN
37,38,ARAKKONAM,181023.0,1317.0,182340.0,Status of EVM Round: 22 /22,Last Updated at 04:18 PM On 05/05/2026,https://results.eci.gov.in/ResultAcGenMay2026/...,NaN
142,143,LALGUDI,183400.0,1813.0,185213.0,Status of EVM Round: 21 /21,Last Updated at 04:18 PM On 05/05/2026,https://results.eci.gov.in/ResultAcGenMay2026/...,NaN
81,82,ATTUR,205764.0,2532.0,208296.0,Status of EVM Round: 23 /23,Last Updated at 04:18 PM On 05/05/2026,https://results.eci.gov.in/ResultAcGenMay2026/...,NaN
143,144,MANACHANALLUR,207351.0,2429.0,209780.0,Status of EVM Round: 22 /22,Last Updated at 04:18 PM On 05/05/2026,https://results.eci.gov.in/ResultAcGenMay2026/...,NaN
128,129,ATHOOR,234114.0,3069.0,237183.0,Status of EVM Round: 26 /26,Last Updated at 04:18 PM On 05/05/2026,https://results.eci.gov.in/ResultAcGenMay2026/...,NaN
218,219,SANKARANKOVIL,192952.0,3528.0,196480.0,Status of EVM Round: 24 /24,Last Updated at 04:18 PM On 05/05/2026,https://results.eci.gov.in/ResultAcGenMay2026/...,NaN
164,165,VEDARANYAM,159383.0,2833.0,162216.0,Status of EVM Round: 18 /18,Last Updated at 04:18 PM On 05/05/2026,https://results.eci.gov.in/ResultAcGenMay2026/...,NaN

In [19]:
dftn["constituency_name"] = (
    dftn["constituency_name"]
    .str.strip()
    .str.lower()

)

In [20]:
dftn.head()

,constituency_no,constituency_name,evm_votes,postal_votes,total_votes_polled,status,last_updated,source_url,error
0,1,gummidipoondi,230900.0,1622.0,232522.0,Status of EVM Round: 26 /26,Last Updated at 04:18 PM On 05/05/2026,https://results.eci.gov.in/ResultAcGenMay2026/...,NaN
1,2,ponneri,225676.0,1143.0,226819.0,Status of EVM Round: 26 /26,Last Updated at 04:18 PM On 05/05/2026,https://results.eci.gov.in/ResultAcGenMay2026/...,NaN
2,3,tiruttani,235620.0,3178.0,238798.0,Status of EVM Round: 27 /27,Last Updated at 04:18 PM On 05/05/2026,https://results.eci.gov.in/ResultAcGenMay2026/...,NaN
3,4,thiruvallur,224649.0,1779.0,226428.0,Status of EVM Round: 24 /24,Last Updated at 04:18 PM On 05/05/2026,https://results.eci.gov.in/ResultAcGenMay2026/...,NaN
4,5,poonamallee,307080.0,1814.0,308894.0,Status of EVM Round: 25 /25,Last Updated at 04:18 PM On 05/05/2026,https://results.eci.gov.in/ResultAcGenMay2026/...,NaN

In [21]:
# convert map keys to lowercase
constituency_map = {
    k.lower(): v.lower()
    for k, v in constituency_map.items()
}

dftn['constituency_name'] = (
    dftn['constituency_name']
    .str.lower()
    .str.strip()
    .replace(constituency_map)
)

In [22]:
dftn.head()

,constituency_no,constituency_name,evm_votes,postal_votes,total_votes_polled,status,last_updated,source_url,error
0,1,gummidipundi,230900.0,1622.0,232522.0,Status of EVM Round: 26 /26,Last Updated at 04:18 PM On 05/05/2026,https://results.eci.gov.in/ResultAcGenMay2026/...,NaN
1,2,ponneri,225676.0,1143.0,226819.0,Status of EVM Round: 26 /26,Last Updated at 04:18 PM On 05/05/2026,https://results.eci.gov.in/ResultAcGenMay2026/...,NaN
2,3,tiruttani,235620.0,3178.0,238798.0,Status of EVM Round: 27 /27,Last Updated at 04:18 PM On 05/05/2026,https://results.eci.gov.in/ResultAcGenMay2026/...,NaN
3,4,thiruvallur,224649.0,1779.0,226428.0,Status of EVM Round: 24 /24,Last Updated at 04:18 PM On 05/05/2026,https://results.eci.gov.in/ResultAcGenMay2026/...,NaN
4,5,poonamallee,307080.0,1814.0,308894.0,Status of EVM Round: 25 /25,Last Updated at 04:18 PM On 05/05/2026,https://results.eci.gov.in/ResultAcGenMay2026/...,NaN

In [23]:
# unique constituency names from both files
df26_const = set(
    df26["constituency"]
    .str.strip()
    .str.lower()
)

scraped_const = set(
    dftn["constituency_name"]
    .str.strip()
    .str.lower()
)

# find what is in df26 but missing in scraped file
missing = df26_const - scraped_const

print("Missing constituency:")
print(missing)

print("\nCount:", len(missing))

Missing constituency:
{'arcot'}

Count: 1

In [24]:
# Add Arcot row
new_row = pd.DataFrame({
    "constituency_name": ["arcot"],
    "total_votes_polled": [225625]
})

dftn = pd.concat([dftn, new_row], ignore_index=True)

# Keep only required columns
dftn = dftn[["constituency_name", "total_votes_polled"]]

print(dftn.tail())

    constituency_name  total_votes_polled
230          colachel            199013.0
231   padmanabhapuram            180555.0
232       vilavancode            174927.0
233         killiyoor            177534.0
234             arcot            225625.0

In [25]:
dftn.head()

  constituency_name  total_votes_polled
0      gummidipundi            232522.0
1           ponneri            226819.0
2         tiruttani            238798.0
3       thiruvallur            226428.0
4       poonamallee            308894.0

In [26]:
df=pd.read_csv("tn_2026_total_electors.csv")

In [27]:
df1=df.copy()

In [28]:
df1.head()

,constituency_no,constituency_name,slug,district,category,total_electors,male_electors,female_electors,third_gender_electors,page_url
0,1,Gummidipoondi,gummidipoondi,Thiruvallur,General,254129,123359,130734,36,https://tnelections2026.in/constituency?name=g...
1,2,Ponneri,ponneri,Thiruvallur,SC,251397,122296,129066,35,https://tnelections2026.in/constituency?name=p...
2,3,Tiruttani,tiruttani,Thiruvallur,General,261857,129401,132431,25,https://tnelections2026.in/constituency?name=t...
3,4,Thiruvallur,thiruvallur,Thiruvallur,General,251018,122198,128784,36,https://tnelections2026.in/constituency?name=t...
4,5,Poonamallee,poonamallee,Thiruvallur,SC,368634,179137,189428,69,https://tnelections2026.in/constituency?name=p...

In [29]:
constituency_map

{'gummidipoondi': 'gummidipundi',
 'palayamkottai': 'palayamcottai',
 'arakkonam': 'arakonam',
 'sholingur': 'sholinghur',
 'viluppuram': 'villupuram',
 'thiyagarayanagar': 'theayagaraya nagar',
 'dr.radhakrishnan nagar': 'dr. radhakrishnan nagar',
 'coimbatore (north)': 'coimbatore north',
 'coimbatore (south)': 'coimbatore south',
 'tiruchirappalli (west)': 'tiruchirapalli (west)',
 'tiruchirappalli (east)': 'tiruchirapalli (east)',
 'senthamangalam': 'sendamangalam',
 'madurantakam': 'maduranthakam',
 'tiruchengodu': 'tiruchengode',
 'rishivandiyam': 'rishivandiam',
 'vaniyambadi': 'vaniayambadi',
 'palacodu': 'palacode',
 'aruppukkottai': 'aruppukottai',
 'edappadi': 'edapadi',
 'ulundurpettai': 'ulundurpet',
 'nilakkottai': 'nilakottai',
 'sirkazhi': 'sirkali',
 'pappireddipatti': 'pappireddippatti',
 'colachal': 'colachel',
 'gudiyattam': 'gudiyatham',
 'mettuppalayam': 'mettupalayam',
 'modakkurichi': 'modakurichi',
 'thiruverumbur': 'thiruverambur',
 'thiruvidaimarudur': 'thiruvidamarudur',
 'mudhukulathur': 'mudukulathur',
 'udumalaipettai': 'udumalpet',
 'aranthangi': 'arantangi',
 'orathanadu': 'orathanad',
 'thiruthuraipoondi': 'thiruthuraipundi'}

In [30]:
df1['constituency_name'] = (
    df1['constituency_name']
    .str.lower()
    .str.strip()
    .replace(constituency_map)
)

In [31]:
df1.head()

,constituency_no,constituency_name,slug,district,category,total_electors,male_electors,female_electors,third_gender_electors,page_url
0,1,gummidipundi,gummidipoondi,Thiruvallur,General,254129,123359,130734,36,https://tnelections2026.in/constituency?name=g...
1,2,ponneri,ponneri,Thiruvallur,SC,251397,122296,129066,35,https://tnelections2026.in/constituency?name=p...
2,3,tiruttani,tiruttani,Thiruvallur,General,261857,129401,132431,25,https://tnelections2026.in/constituency?name=t...
3,4,thiruvallur,thiruvallur,Thiruvallur,General,251018,122198,128784,36,https://tnelections2026.in/constituency?name=t...
4,5,poonamallee,poonamallee,Thiruvallur,SC,368634,179137,189428,69,https://tnelections2026.in/constituency?name=p...

In [32]:

dftn.shape

(235, 2)

In [33]:
df1.shape

(234, 10)

In [34]:
dftn_const = set(
    dftn["constituency_name"]
    .str.strip()
    .str.lower()
)

df1_const = set(
    df1["constituency_name"]
    .str.strip()
    .str.lower()
)

# find what is in df26 but missing in scraped file
missing = dftn_const - df1_const

print("Missing constituency:")
print(missing)

print("\nCount:", len(missing))

Missing constituency:
{nan, 'theayagaraya nagar', 'dr. radhakrishnan nagar', 'gandharvakottai'}

Count: 4

In [35]:
print(dftn["constituency_name"].isna().sum())

1

In [36]:
dftn = dftn.dropna(
    subset=["constituency_name"]
)

In [37]:
dftn_const = set(
    dftn["constituency_name"]
    .str.strip()
    .str.lower()
)

df1_const = set(
    df1["constituency_name"]
    .str.strip()
    .str.lower()
)

missing = dftn_const - df1_const

print(missing)

{'theayagaraya nagar', 'dr. radhakrishnan nagar', 'gandharvakottai'}

In [38]:
df1.shape

(234, 10)

In [39]:
dftn.shape

(234, 2)

In [40]:
constituency_map.update({
    "dr radhakrishnan nagar":"dr. radhakrishnan nagar",
    "theayagarayanagar":"theayagaraya nagar",
    "gandarvakottai":"gandharvakottai"
})

In [41]:
# remove NaN
dftn = dftn.dropna(subset=["constituency_name"])

# recreate sets AFTER cleaning
dftn_const = set(
    dftn["constituency_name"]
    .str.strip()
    .str.lower()
)

df1_const = set(
    df1["constituency_name"]
    .str.strip()
    .str.lower()
)

print("Rows:")
print("dftn:", dftn.shape[0])
print("df1:", df1.shape[0])

print("\nUnique constituencies:")
print("dftn:", len(dftn_const))
print("df1:", len(df1_const))

missing = dftn_const - df1_const

print("\nMissing:")
print(sorted(missing))
print("Count:", len(missing))

Rows:
dftn: 234
df1: 234

Unique constituencies:
dftn: 233
df1: 234

Missing:
['dr. radhakrishnan nagar', 'gandharvakottai', 'theayagaraya nagar']
Count: 3

In [42]:
extra = df1_const - dftn_const

print("Extra in df1:")
print(extra)

print("Count:", len(extra))

Extra in df1:
{'tirupattur', 'gandarvakkottai', 'rk nagar', 't nagar'}
Count: 4

In [45]:
dftn['constituency_name'].unique()

array(['gummidipundi', 'ponneri', 'tiruttani', 'thiruvallur',
       'poonamallee', 'avadi', 'maduravoyal', 'ambattur', 'madavaram',
       'thiruvottiyur', 'dr. radhakrishnan nagar', 'perambur', 'kolathur',
       'villivakkam', 'thiru-vi-ka-nagar', 'egmore', 'royapuram',
       'harbour', 'chepauk-thiruvallikeni', 'thousand lights',
       'anna nagar', 'virugampakkam', 'saidapet', 'theayagaraya nagar',
       'mylapore', 'velachery', 'shozhinganallur', 'alandur',
       'sriperumbudur', 'pallavaram', 'tambaram', 'chengalpattu',
       'thiruporur', 'cheyyur', 'maduranthakam', 'uthiramerur',
       'kancheepuram', 'arakonam', 'sholinghur', 'katpadi', 'ranipet',
       'vellore', 'anaikattu', 'kilvaithinankuppam', 'gudiyatham',
       'vaniayambadi', 'ambur', 'jolarpet', 'tiruppattur', 'uthangarai',
       'bargur', 'krishnagiri', 'veppanahalli', 'hosur', 'thalli',
       'palacode', 'pennagaram', 'dharmapuri', 'pappireddippatti',
       'harur', 'chengam', 'tiruvannamalai', 'kilpennathur',
       'kalasapakkam', 'polur', 'arani', 'cheyyar', 'vandavasi', 'gingee',
       'mailam', 'tindivanam', 'vanur', 'villupuram', 'vikravandi',
       'tirukkoyilur', 'ulundurpet', 'rishivandiam', 'sankarapuram',
       'kallakurichi', 'gangavalli', 'attur', 'yercaud', 'omalur',
       'mettur', 'edapadi', 'sankari', 'salem (west)', 'salem (north)',
       'salem (south)', 'veerapandi', 'rasipuram', 'sendamangalam',
       'namakkal', 'paramathi-velur', 'tiruchengode', 'kumarapalayam',
       'erode (east)', 'erode (west)', 'modakurichi', 'dharapuram',
       'kangayam', 'perundurai', 'bhavani', 'anthiyur',
       'gobichettipalayam', 'bhavanisagar', 'udhagamandalam', 'gudalur',
       'coonoor', 'mettupalayam', 'avanashi', 'tiruppur (north)',
       'tiruppur (south)', 'palladam', 'sulur', 'kavundampalayam',
       'coimbatore north', 'thondamuthur', 'coimbatore south',
       'singanallur', 'kinathukadavu', 'pollachi', 'valparai',
       'udumalpet', 'madathukulam', 'palani', 'oddanchatram', 'athoor',
       'nilakottai', 'natham', 'dindigul', 'vedasandur', 'aravakurichi',
       'karur', 'krishnarayapuram', 'kulithalai', 'manapparai',
       'srirangam', 'tiruchirapalli (west)', 'tiruchirapalli (east)',
       'thiruverambur', 'lalgudi', 'manachanallur', 'musiri', 'thuraiyur',
       'perambalur', 'kunnam', 'ariyalur', 'jayankondam', 'tittakudi',
       'vriddhachalam', 'neyveli', 'panruti', 'cuddalore', 'kurinjipadi',
       'bhuvanagiri', 'chidambaram', 'kattumannarkoil', 'sirkali',
       'mayiladuthurai', 'poompuhar', 'nagapattinam', 'kilvelur',
       'vedaranyam', 'thiruthuraipundi', 'mannargudi', 'thiruvarur',
       'nannilam', 'thiruvidamarudur', 'kumbakonam', 'papanasam',
       'thiruvaiyaru', 'thanjavur', 'orathanad', 'pattukkottai',
       'peravurani', 'gandharvakottai', 'viralimalai', 'pudukkottai',
       'thirumayam', 'alangudi', 'arantangi', 'karaikudi', 'sivaganga',
       'manamadurai', 'melur', 'madurai east', 'sholavandan',
       'madurai north', 'madurai south', 'madurai central',
       'madurai west', 'thiruparankundram', 'thirumangalam',
       'usilampatti', 'andipatti', 'periyakulam', 'bodinayakanur',
       'cumbum', 'rajapalayam', 'srivilliputhur', 'sattur', 'sivakasi',
       'virudhunagar', 'aruppukottai', 'tiruchuli', 'paramakudi',
       'tiruvadanai', 'ramanathapuram', 'mudukulathur', 'vilathikulam',
       'thoothukkudi', 'tiruchendur', 'srivaikuntam', 'ottapidaram',
       'kovilpatti', 'sankarankovil', 'vasudevanallur', 'kadayanallur',
       'tenkasi', 'alangulam', 'tirunelveli', 'ambasamudram',
       'palayamcottai', 'nanguneri', 'radhapuram', 'kanniyakumari',
       'nagercoil', 'colachel', 'padmanabhapuram', 'vilavancode',
       'killiyoor', 'arcot'], dtype=object)

In [46]:
print(
    dftn["constituency_name"]
    .value_counts()
    [lambda x: x > 1]
)

constituency_name
tiruppattur    2
Name: count, dtype: int64

In [47]:
missing = df1_const - dftn_const

print("\nMissing:")
print(sorted(missing))
print("Count:", len(missing))

Missing:
['gandarvakkottai', 'rk nagar', 't nagar', 'tirupattur']
Count: 4

In [48]:
fix_map = {
    "rk nagar": "dr. radhakrishnan nagar",
    "t nagar": "theayagaraya nagar",
    "gandarvakkottai": "gandharvakottai"
}

df1["constituency_name"] = (
    df1["constituency_name"]
    .str.lower()
    .str.strip()
    .replace(fix_map)
)

In [51]:
# recreate sets AFTER cleaning
dftn_const2 = set(
    dftn["constituency_name"]
    .str.strip()
    .str.lower()
)

df1_const2 = set(
    df1["constituency_name"]
    .str.strip()
    .str.lower()
)
missing2 = df1_const2 - dftn_const2

print("\nMissing:")
print(sorted(missing2))
print("Count:", len(missing2))

Missing:
['tirupattur']
Count: 1

In [53]:
missing3 = dftn_const2 - df1_const2

print("\nMissing:")
print(sorted(missing3))
print("Count:", len(missing3))

Missing:
[]
Count: 0

In [54]:
dftn.shape

(234, 2)

In [55]:
df1.shape

(234, 10)

In [56]:
dftn = dftn.drop_duplicates(
    subset=["constituency_name"],
    keep="first"
)

print(dftn.shape)

(233, 2)

In [57]:
df1 = df1.drop_duplicates(
    subset=["constituency_name"],
    keep="first"
)

print(df1.shape)

(234, 10)

In [58]:
fix_map = {
    "tiruppattur": "tirupattur"
}
dftn["constituency_name"] = (
    dftn["constituency_name"]
    .str.lower()
    .str.strip()
    .replace(fix_map)
)

/tmp/ipykernel_1222/2321735573.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftn["constituency_name"] = (

In [59]:
# recreate sets AFTER cleaning
dftn_const3 = set(
    dftn["constituency_name"]
    .str.strip()
    .str.lower()
)

df1_const3 = set(
    df1["constituency_name"]
    .str.strip()
    .str.lower()
)
missing2 = df1_const3 - dftn_const3

print("\nMissing:")
print(sorted(missing3))
print("Count:", len(missing3))

Missing:
[]
Count: 0

In [60]:
dftn.shape

(233, 2)

In [61]:
df1.shape

(234, 10)

In [62]:
print(
    dftn["constituency_name"]
    .value_counts()
    [lambda x: x > 1]
)

Series([], Name: count, dtype: int64)

In [63]:
print(
    df1["constituency_name"]
    .value_counts()
    [lambda x: x > 1]
)

Series([], Name: count, dtype: int64)

In [64]:
print("dftn rows:", len(dftn))
print("dftn unique:", dftn["constituency_name"].nunique())

print("df1 rows:", len(df1))
print("df1 unique:", df1["constituency_name"].nunique())

# Check nulls
print("\ndftn nulls:", dftn["constituency_name"].isna().sum())
print("df1 nulls:", df1["constituency_name"].isna().sum())

# Check duplicates directly
print("\ndftn duplicates:")
print(
    dftn["constituency_name"][
        dftn["constituency_name"].duplicated(keep=False)
    ]
)

print("\ndf1 duplicates:")
print(
    df1["constituency_name"][
        df1["constituency_name"].duplicated(keep=False)
    ]
)

dftn rows: 233
dftn unique: 233
df1 rows: 234
df1 unique: 234

dftn nulls: 0
df1 nulls: 0

dftn duplicates:
Series([], Name: constituency_name, dtype: object)

df1 duplicates:
Series([], Name: constituency_name, dtype: object)

In [65]:
dftn_const = set(
    dftn["constituency_name"]
    .str.strip()
    .str.lower()
)

df1_const = set(
    df1["constituency_name"]
    .str.strip()
    .str.lower()
)

print("Missing from dftn:")
print(df1_const - dftn_const)

print("\nCount:")
print(len(df1_const - dftn_const))

Missing from dftn:
{'tiruppattur'}

Count:
1

In [66]:
value = dftn.loc[
    dftn["constituency_name"] == "tirupattur",
    "total_votes_polled"
].iloc[0]

print(value)

202925.0

In [67]:
new_row = pd.DataFrame({
    "constituency_name": ["tiruppattur"],
    "total_votes_polled": [214303]
})

dftn = pd.concat([dftn, new_row], ignore_index=True)

print(
    dftn.tail()
)

    constituency_name  total_votes_polled
229   padmanabhapuram            180555.0
230       vilavancode            174927.0
231         killiyoor            177534.0
232             arcot            225625.0
233       tiruppattur            214303.0

In [68]:
print("dftn rows:", len(dftn))
print("dftn unique:", dftn["constituency_name"].nunique())

print("df1 rows:", len(df1))
print("df1 unique:", df1["constituency_name"].nunique())

# Check nulls
print("\ndftn nulls:", dftn["constituency_name"].isna().sum())
print("df1 nulls:", df1["constituency_name"].isna().sum())

# Check duplicates directly
print("\ndftn duplicates:")
print(
    dftn["constituency_name"][
        dftn["constituency_name"].duplicated(keep=False)
    ]
)

print("\ndf1 duplicates:")
print(
    df1["constituency_name"][
        df1["constituency_name"].duplicated(keep=False)
    ]
)

dftn rows: 234
dftn unique: 234
df1 rows: 234
df1 unique: 234

dftn nulls: 0
df1 nulls: 0

dftn duplicates:
Series([], Name: constituency_name, dtype: object)

df1 duplicates:
Series([], Name: constituency_name, dtype: object)

In [69]:
master.shape

(234, 5)

In [70]:
df1.head()

,constituency_no,constituency_name,slug,district,category,total_electors,male_electors,female_electors,third_gender_electors,page_url
0,1,gummidipundi,gummidipoondi,Thiruvallur,General,254129,123359,130734,36,https://tnelections2026.in/constituency?name=g...
1,2,ponneri,ponneri,Thiruvallur,SC,251397,122296,129066,35,https://tnelections2026.in/constituency?name=p...
2,3,tiruttani,tiruttani,Thiruvallur,General,261857,129401,132431,25,https://tnelections2026.in/constituency?name=t...
3,4,thiruvallur,thiruvallur,Thiruvallur,General,251018,122198,128784,36,https://tnelections2026.in/constituency?name=t...
4,5,poonamallee,poonamallee,Thiruvallur,SC,368634,179137,189428,69,https://tnelections2026.in/constituency?name=p...

In [71]:
dftn.head()

  constituency_name  total_votes_polled
0      gummidipundi            232522.0
1           ponneri            226819.0
2         tiruttani            238798.0
3       thiruvallur            226428.0
4       poonamallee            308894.0

In [72]:
# Merge datasets
final_df = dftn.merge(
    df1[["constituency_name", "total_electors"]],
    on="constituency_name",
    how="inner"
)

# Calculate voter turnout percentage
final_df["voter_turnout"] = (
    final_df["total_votes_polled"]
    / final_df["total_electors"]
) * 100

# Round to 2 decimals
final_df["voter_turnout"] = (
    final_df["voter_turnout"]
    .round(2)
)

print(final_df.head())
print(final_df.shape)

  constituency_name  total_votes_polled  total_electors  voter_turnout
0      gummidipundi            232522.0          254129          91.50
1           ponneri            226819.0          251397          90.22
2         tiruttani            238798.0          261857          91.19
3       thiruvallur            226428.0          251018          90.20
4       poonamallee            308894.0          368634          83.79
(234, 4)

In [73]:
final_df.head()

  constituency_name  total_votes_polled  total_electors  voter_turnout
0      gummidipundi            232522.0          254129          91.50
1           ponneri            226819.0          251397          90.22
2         tiruttani            238798.0          261857          91.19
3       thiruvallur            226428.0          251018          90.20
4       poonamallee            308894.0          368634          83.79

In [78]:
from google.colab import files

# Export CSVs
df1.to_csv("df1.csv", index=False)
dftn.to_csv("dftn.csv", index=False)
final_df.to_csv("final_df.csv", index=False)

# Download to your PC
files.download("df1.csv")
files.download("dftn.csv")
files.download("final_df.csv")

In [79]:
df26.shape

(4257, 8)

In [80]:
len(df26['constituency'].unique())

233

In [81]:
# standardize master names
master["constituency"] = (
    master["constituency"]
    .str.lower()
    .str.strip()
)

# create sets
master_const = set(master["constituency"])

dftn_const = set(
    dftn["constituency_name"]
    .str.lower()
    .str.strip()
)

# compare both directions
missing_in_dftn = master_const - dftn_const
extra_in_dftn = dftn_const - master_const

print("Present in master but missing in dftn:")
print(sorted(missing_in_dftn))
print("Count:", len(missing_in_dftn))

print("\nPresent in dftn but not in master:")
print(sorted(extra_in_dftn))
print("Count:", len(extra_in_dftn))

Present in master but missing in dftn:
[]
Count: 0

Present in dftn but not in master:
['tirupattur']
Count: 1

In [82]:
print(
    master["constituency"]
    .value_counts()
    [lambda x: x > 1]
)

constituency
tiruppattur    2
Name: count, dtype: int64

In [83]:
dup_names = master["constituency"][
    master["constituency"].duplicated(keep=False)
]

print(
    master[
        master["constituency"]
        .isin(dup_names)
    ]
)

     ac_number constituency   district region reserved
49          50  tiruppattur    Vellore  North      GEN
184        185  tiruppattur  Sivaganga  South      GEN

In [84]:
master.loc[
    master["ac_number"] == 50,
    "constituency"
] = "tirupattur"

In [85]:
print(
    master["constituency"]
    .value_counts()
    [lambda x: x > 1]
)

Series([], Name: count, dtype: int64)

In [86]:
print("df21:")
print(
    df21.loc[
        df21["ac_number"] == 50,
        ["ac_number","constituency","candidate","party","votes"]
    ]
)

df21:
     ac_number constituency             candidate  \
960         50  Tiruppattur        A. NALLATHAMBI
961         50  Tiruppattur             T.K. RAJA
962         50  Tiruppattur            M. SUMATHI
963         50  Tiruppattur         A. GNANASEKAR
964         50  Tiruppattur     None Of The Above
965         50  Tiruppattur        B. VIJAYAKUMAR
966         50  Tiruppattur         S. KALASHTHRI
967         50  Tiruppattur     S. SATHIYAMOORTHY
968         50  Tiruppattur  R. AROCKIA JOE PRABU
969         50  Tiruppattur             R. PALANI
970         50  Tiruppattur         M. NALLASIVAM
971         50  Tiruppattur              MANITHAN
972         50  Tiruppattur        I. GOVINDARAJI
973         50  Tiruppattur      I. ROSELIN JEEVA
974         50  Tiruppattur               G. RAJA
975         50  Tiruppattur            A. JEYAMMA

                                          party  votes
960                                         DMK  96522
961                                         PMK  68282
962                                         NTK  12127
963                                        AMMK   2702
964                                        NOTA   1632
965                                         IND   1096
966  All India Uzhavargal Uzhaippalargal Katchi    724
967                        Makkal Nala Kazhagam    519
968                                         IND    438
969                                         IND    362
970                                         IND    323
971                                         IND    309
972                                         IND    297
973                 Samaniya Makkal Nala Katchi    264
974                                         IND    205
975              Anaithu Makkal Puratchi Katchi    128

In [87]:
print("\ndf26:")
print(
    df26.loc[
        df26["ac_number"] == 50,
        ["ac_number","constituency","candidate","party","votes"]
    ]
)

df26:
      ac_number constituency          candidate  \
986          50  Tiruppattur   DR.THIRUPATHI. N
987          50  Tiruppattur     NALLATHAMBI. A
988          50  Tiruppattur      GNANASEKAR. A
989          50  Tiruppattur        ARUMUGAM. V
990          50  Tiruppattur          RAJESH. S
991          50  Tiruppattur               NOTA
992          50  Tiruppattur      THIRUPATHI. N
993          50  Tiruppattur      VENKATESAN. K
994          50  Tiruppattur           SEKAR. N
995          50  Tiruppattur    RAJIV GANDHI. S
996          50  Tiruppattur      THIRUPATHI. C
997          50  Tiruppattur     VIJAYAKUMAR. G
998          50  Tiruppattur      THIRUPATHI. S
999          50  Tiruppattur      RAGUJOSEPH. J
1000         50  Tiruppattur      KALASTHIRI. S
1001         50  Tiruppattur    GNANASEKARAN. R
1002         50  Tiruppattur     NALLATHAMBI. R
1003         50  Tiruppattur          SANKAR. S
1004         50  Tiruppattur    DR.POOVALAGI. P
1005         50  Tiruppattur  SATHIYAMOORTHY. S
1006         50  Tiruppattur  BALABHARATHI. S.V
1007         50  Tiruppattur    GNANASEKARAN. M
1008         50  Tiruppattur       MOHAN RAJ. R
1009         50  Tiruppattur          ANJALI. M
1010         50  Tiruppattur        GOVIND. T.G

                                              party   votes
986                                             TVK  105098
987                                             DMK   56835
988                                            AMMK   30003
989                                             NTK    5482
990                   Tamizhaga Vaazhvurimai Katchi     486
991                                            NOTA     464
992                                             IND     447
993                                             IND     408
994               All India Youth Development Party     387
995                             Bahujan Samaj Party     361
996                                             IND     355
997   Aanaithinthiya Jananayaka Pathukappu Kazhagam     345
998                                             IND     339
999                                             IND     308
1000     All India Uzhavargal Uzhaippalargal Katchi     208
1001                                            IND     206
1002                                            IND     192
1003                                            IND     182
1004                                            IND     139
1005                           Makkal Nala Kazhagam     136
1006                                            IND     128
1007                                            IND     127
1008                                            IND     119
1009                                            IND     115
1010                                            IND      55

In [88]:
print("df21:")
print(
    df21.loc[
        df21["ac_number"] == 185,
        ["ac_number","constituency","candidate","party","votes"]
    ]
)

df21:
      ac_number constituency             candidate  \
3313        185  Tiruppattur     KR.PERIYAKARUPPAN
3314        185  Tiruppattur      MARUDHU ALAGURAJ
3315        185  Tiruppattur           KOTTAIKUMAR
3316        185  Tiruppattur         C.PARAMASIVAM
3317        185  Tiruppattur         K.K.UMADHEVAN
3318        185  Tiruppattur  A.AMALAN SAVARIMUTHU
3319        185  Tiruppattur     None Of The Above
3320        185  Tiruppattur            PERIYASAMY
3321        185  Tiruppattur       A.PARTHASARATHY
3322        185  Tiruppattur             A.MALLIKA
3323        185  Tiruppattur          K.S.K.RAJESH
3324        185  Tiruppattur           PALANIAPPAN
3325        185  Tiruppattur          M.SARASWATHI
3326        185  Tiruppattur            P.SELVARAJ
3327        185  Tiruppattur           P.RAJESWARI
3328        185  Tiruppattur        K.VEERAPANDIAN
3329        185  Tiruppattur      M.MOHAMED RABEEK
3330        185  Tiruppattur        P.JEYACHANDRAN
3331        185  Tiruppattur             S.MURUGAN
3332        185  Tiruppattur  G.ABDUL KISHORE BABU
3333        185  Tiruppattur            A.KARTHIKA
3334        185  Tiruppattur          RM.MURUGESAN
3335        185  Tiruppattur              C.KANNAN
3336        185  Tiruppattur          MUTHULAKSHMI
3337        185  Tiruppattur             J.VEERAYI
3338        185  Tiruppattur            ANANDHAN K
3339        185  Tiruppattur                RENUKA

                               party   votes
3313                             DMK  103682
3314                          AIADMK   66308
3315                             NTK   14571
3316                             IND   13202
3317                            AMMK    7448
3318                             IJK     862
3319                            NOTA     853
3320                             IND     605
3321                             IND     465
3322                             IND     444
3323                             IND     352
3324                             IND     333
3325               Puthiya Tamilagam     241
3326                             IND     221
3327                             IND     152
3328                  My India Party     144
3329                             IND     122
3330                             IND     115
3331  Anaithu Makkal Puratchi Katchi      96
3332                             IND      85
3333                             IND      80
3334                             IND      69
3335                             IND      68
3336                             IND      65
3337                             IND      65
3338                             IND      62
3339                             IND      56

In [89]:
print("df26:")
print(
    df26.loc[
        df26["ac_number"] == 185,
        ["ac_number","constituency","candidate","party","votes"]
    ]
)

df26:
      ac_number constituency                 candidate  \
3404        185  Tiruppattur   SEENIVASA SETHUPATHY. R
3405        185  Tiruppattur         PERIAKARUPPAN. KR
3406        185  Tiruppattur           THIRUMARAN. K.C
3407        185  Tiruppattur               RAMYA MOHAN
3408        185  Tiruppattur               RAJA. K.P.M
3409        185  Tiruppattur                      NOTA
3410        185  Tiruppattur                UMADEVI. S
3411        185  Tiruppattur           VISHWANATHAN. S
3412        185  Tiruppattur              SHANMUGAM. M
3413        185  Tiruppattur  DR.VINAYAGA MEYYARASU. T
3414        185  Tiruppattur              MARIMUTHU. S
3415        185  Tiruppattur          BAKIYALAKSHMI. M
3416        185  Tiruppattur                PIRAMAN. P
3417        185  Tiruppattur                MALLIKA. A
3418        185  Tiruppattur                  SETHU. P
3419        185  Tiruppattur           PANCHAVARNAM. M

                                                  party  votes
3404                                                TVK  83375
3405                                                DMK  83374
3406                                                BJP  29054
3407                                                NTK  15291
3408                                                IND    753
3409                                               NOTA    747
3410  All India Puratchi Thalaivar Makkal Munnettra ...    611
3411                                                IND    496
3412                                                IND    383
3413                                                IND    380
3414                                                IND    350
3415                                                IND    266
3416                                                IND    223
3417                                                IND    143
3418                                                IND    135
3419                                                IND    129

In [90]:
df21.loc[
    df21["ac_number"] == 50,
    "constituency"
] = "tirupattur"

In [91]:
df26.loc[
    df26["ac_number"] == 50,
    "constituency"
] = "tirupattur"

In [94]:
print("df26:")
print(
    df26.loc[
        df26["ac_number"] == 185,
        ["ac_number","constituency","candidate","party","votes"]
    ]
)

df26:
      ac_number constituency                 candidate  \
3404        185  Tiruppattur   SEENIVASA SETHUPATHY. R
3405        185  Tiruppattur         PERIAKARUPPAN. KR
3406        185  Tiruppattur           THIRUMARAN. K.C
3407        185  Tiruppattur               RAMYA MOHAN
3408        185  Tiruppattur               RAJA. K.P.M
3409        185  Tiruppattur                      NOTA
3410        185  Tiruppattur                UMADEVI. S
3411        185  Tiruppattur           VISHWANATHAN. S
3412        185  Tiruppattur              SHANMUGAM. M
3413        185  Tiruppattur  DR.VINAYAGA MEYYARASU. T
3414        185  Tiruppattur              MARIMUTHU. S
3415        185  Tiruppattur          BAKIYALAKSHMI. M
3416        185  Tiruppattur                PIRAMAN. P
3417        185  Tiruppattur                MALLIKA. A
3418        185  Tiruppattur                  SETHU. P
3419        185  Tiruppattur           PANCHAVARNAM. M

                                                  party  votes
3404                                                TVK  83375
3405                                                DMK  83374
3406                                                BJP  29054
3407                                                NTK  15291
3408                                                IND    753
3409                                               NOTA    747
3410  All India Puratchi Thalaivar Makkal Munnettra ...    611
3411                                                IND    496
3412                                                IND    383
3413                                                IND    380
3414                                                IND    350
3415                                                IND    266
3416                                                IND    223
3417                                                IND    143
3418                                                IND    135
3419                                                IND    129

In [95]:
for df in [df21, df26]:
    df["constituency"] = (
        df["constituency"]
        .str.lower()
        .str.strip()
    )

In [96]:
print("df26:")
print(
    df26.loc[
        df26["ac_number"] == 185,
        ["ac_number","constituency","candidate","party","votes"]
    ]
)

df26:
      ac_number constituency                 candidate  \
3404        185  tiruppattur   SEENIVASA SETHUPATHY. R
3405        185  tiruppattur         PERIAKARUPPAN. KR
3406        185  tiruppattur           THIRUMARAN. K.C
3407        185  tiruppattur               RAMYA MOHAN
3408        185  tiruppattur               RAJA. K.P.M
3409        185  tiruppattur                      NOTA
3410        185  tiruppattur                UMADEVI. S
3411        185  tiruppattur           VISHWANATHAN. S
3412        185  tiruppattur              SHANMUGAM. M
3413        185  tiruppattur  DR.VINAYAGA MEYYARASU. T
3414        185  tiruppattur              MARIMUTHU. S
3415        185  tiruppattur          BAKIYALAKSHMI. M
3416        185  tiruppattur                PIRAMAN. P
3417        185  tiruppattur                MALLIKA. A
3418        185  tiruppattur                  SETHU. P
3419        185  tiruppattur           PANCHAVARNAM. M

                                                  party  votes
3404                                                TVK  83375
3405                                                DMK  83374
3406                                                BJP  29054
3407                                                NTK  15291
3408                                                IND    753
3409                                               NOTA    747
3410  All India Puratchi Thalaivar Makkal Munnettra ...    611
3411                                                IND    496
3412                                                IND    383
3413                                                IND    380
3414                                                IND    350
3415                                                IND    266
3416                                                IND    223
3417                                                IND    143
3418                                                IND    135
3419                                                IND    129

In [97]:
len(df26['constituency'].unique())

234

In [98]:
len(df21['constituency'].unique())

234

In [99]:
master.shape[0]

234

In [100]:
df26.drop(columns=["turnout"], inplace=True)

In [101]:
df261=df26.copy()

In [104]:
df261 = df261.merge(
    final_df.rename(
        columns={"constituency_name": "constituency"}
    )[["constituency", "voter_turnout"]],
    on="constituency",
    how="left"
)

print(df261.head())

   constituency  ac_number         candidate   party  votes reserved  \
0  gummidipundi          1     S.VIJAYAKUMAR     TVK  94320      GEN
1  gummidipundi          1        SUDHAKAR.V  AIADMK  66375      GEN
2  gummidipundi          1  T.J.GOVINDARAJAN     DMK  62492      GEN
3  gummidipundi          1   R.SRIDAR. B.L.,     NTK   4756      GEN
4  gummidipundi          1              NOTA    NOTA    937      GEN

          region  voter_turnout_x  voter_turnout_y
0  Chennai Metro             91.5             91.5
1  Chennai Metro             91.5             91.5
2  Chennai Metro             91.5             91.5
3  Chennai Metro             91.5             91.5
4  Chennai Metro             91.5             91.5

In [105]:
df261.drop(columns=["voter_turnout_y"], inplace=True)

In [106]:
df261.head()

,constituency,ac_number,candidate,party,votes,reserved,region,voter_turnout_x
0,gummidipundi,1,S.VIJAYAKUMAR,TVK,94320,GEN,Chennai Metro,91.5
1,gummidipundi,1,SUDHAKAR.V,AIADMK,66375,GEN,Chennai Metro,91.5
2,gummidipundi,1,T.J.GOVINDARAJAN,DMK,62492,GEN,Chennai Metro,91.5
3,gummidipundi,1,"R.SRIDAR. B.L.,",NTK,4756,GEN,Chennai Metro,91.5
4,gummidipundi,1,NOTA,NOTA,937,GEN,Chennai Metro,91.5

In [107]:
master.head()

   ac_number  constituency    district         region reserved
0          1  gummidipundi  Tiruvallur  Chennai Metro      GEN
1          2       ponneri  Tiruvallur  Chennai Metro       SC
2          3     tiruttani  Tiruvallur  Chennai Metro      GEN
3          4   thiruvallur  Tiruvallur  Chennai Metro      GEN
4          5   poonamallee  Tiruvallur  Chennai Metro       SC

In [108]:
df211=df21.copy()

In [109]:
master1=master.copy()

In [110]:
from google.colab import files

# Export CSVs
df1.to_csv("df211.csv", index=False)
dftn.to_csv("df261.csv", index=False)
final_df.to_csv("master1.csv", index=False)

# Download to your PC
files.download("df211.csv")
files.download("df261.csv")
files.download("master1.csv")